name: catch2

on: [push, pull_request]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: mkdir $GITHUB_WORKSPACE/molfunc/build

      - name: Configure CMake
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && cmake .. -DCMAKE_BUILD_TYPE=$BUILD_TYPE


      - name: Build
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && cmake --build . --config $BUILD_TYPE

      - name: Test
        shell: bash
        run: cd $GITHUB_WORKSPACE/molfunc/build && ctest -C $BUILD_TYPE --extra-verbose
